name: K3OS Image CI

on: [push]

jobs:

  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the image
      run: make
    - name: Run the image
      run: bash ./scripts/run
